version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: github/thallesrangel/book-db
    container_name: book-db
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/webapi-mvc
    volumes:
      - api-go-book:/var/lib/postgresql/data

volumes:
  api-go-book: